on:
  push:
    branches: main
  schedule:
    - cron: '0 1 * * *'

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - name: Install packages
        run: |
          Rscript -e 'install.packages("rmarkdown")'
          Rscript -e 'install.packages("leaflet")'
          Rscript -e 'install.packages("purrr")'
          Rscript -e 'install.packages("tibble")'
          Rscript -e 'install.packages("tidyverse")'
          Rscript -e 'install.packages("plotly")'
          Rscript -e 'install.packages("knitr")'
          Rscript -e 'install.packages("tidyr")'
          Rscript -e 'install.packages("dplyr")'
          Rscript -e 'install.packages("openssl")'
      - name: Render README
        env: 
          TEST_SECRET: ${{ secrets.TEST_SECRET}}
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "html_document")'
      - name: Render contributeside
        env: 
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET}}
        run: Rscript -e 'rmarkdown::render("contribute.Rmd", output_format = "html_document")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A .
          git commit -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"